(() => {
  "use strict";
  const RK="fuel_guard_routines_v1", OK="fuel_guard_routine_occurrences_v1", DAYS=["Sun","Mon","Tue","Wed","Thu","Fri","Sat"], LOOKBACK=7;
  const CATALOGUE=[
    ["creatine","Creatine"],["protein_supplement","Protein powder"],["iron","Iron"],["vitamin_d","Vitamin D"],["vitamin_c","Vitamin C"],["vitamin_b12","Vitamin B12"],["multivitamin","Multivitamin"],["magnesium","Magnesium"],["zinc","Zinc"],["calcium","Calcium"],["omega_3","Omega-3 / Fish oil"],["electrolytes","Electrolytes"],["caffeine","Caffeine","custom"],["collagen","Collagen","custom"],["folic_acid","Folic acid","custom"],["probiotics","Probiotics","custom"],["beta_alanine","Beta-alanine","custom"],["nitrate_beetroot","Nitrate / Beetroot","custom"],["carbohydrate_supplement","Carbohydrate supplement","custom"],["recovery_drink","Recovery drink","custom"]
  ];
  let plans=[],busy=false,message="";
  const cloud=()=>window.fuelGuardCloud||null, uid=()=>String(cloud()?.user?.id||"");
  const id=()=>crypto?.randomUUID?.()||`routine-${Date.now()}-${Math.random().toString(16).slice(2)}`;
  const esc=v=>window.FuelGuardDomain?.escapeHtml?.(String(v??""))||String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
  const read=(k,f)=>{try{return JSON.parse(localStorage.getItem(k)||"null")??f}catch{return f}}, write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
  const routines=()=>read(RK,[]).filter(x=>x?.id), occ=()=>read(OK,{}), saveR=v=>write(RK,v), saveO=v=>write(OK,v);
  const dateKey=(d=new Date())=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;
  const planned=(r,d=new Date())=>{const x=new Date(d),[h,m]=String(r.time||"08:00").split(":").map(Number);x.setHours(h||0,m||0,0,0);return x};
  const clock=d=>d.toLocaleTimeString([],{hour:"numeric",minute:"2-digit"}), dayLabel=d=>d.toLocaleDateString([],{weekday:"short",day:"numeric",month:"short"});
  const okey=(r,d=new Date())=>`${dateKey(d)}:${r.id}`, onDay=(r,d)=>r.enabled!==false&&(r.days||[]).includes(d.getDay());
  const planLabel=p=>p?.label||p?.custom_name||"Supplement";
  const activeFor=r=>plans.filter(p=>(r.supplementPlanIds||[]).includes(p.id));
  const labels=r=>[...(r.coffee?["Coffee"]:[]),...activeFor(r).map(planLabel)];
  const daysText=a=>a?.length===7?"Daily":(a||[]).map(x=>DAYS[x]).join(", ");
  const catalogueKey=p=>p.supplement_type!=="custom"?p.supplement_type:(CATALOGUE.find(x=>x[2]==="custom"&&x[1].toLowerCase()===String(p.custom_name||p.label||"").toLowerCase())?.[0]||"");
  function durationHuman(min){if(!Number.isFinite(min))return"No limit";const n=Math.max(0,Math.round(min));if(n>=1440){const d=Math.floor(n/1440);return`${d} day${d===1?"":"s"}`}return`${Math.floor(n/60)}h ${String(n%60).padStart(2,"0")}m`} globalThis.duration=durationHuman;

  async function loadPlans(){if(!cloud()?.client||!uid()){plans=[];return}const {data,error}=await cloud().client.from("fuel_supplement_plans").select("id,label,custom_name,supplement_type,active").eq("user_id",uid()).eq("active",true).order("created_at");if(!error)plans=data||[]}
  async function ensurePlans(keys){
    if(!keys.length)return[]; if(!cloud()?.client||!uid())throw new Error("Sign in to save supplement routines.");
    const selected=[];
    for(const key of keys){let p=plans.find(x=>catalogueKey(x)===key);if(p){selected.push(p);continue}const c=CATALOGUE.find(x=>x[0]===key);if(!c)continue;const type=c[2]||c[0];const row={id:id(),user_id:uid(),supplement_type:type,custom_name:type==="custom"?c[1]:null,label:c[1],active:true,track_caffeine_separation:false};const {data,error}=await cloud().client.from("fuel_supplement_plans").insert(row).select().single();if(error)throw error;p=data;plans.push(p);selected.push(p)}
    return selected;
  }

  function ensureSurfaces(){
    const quick=document.querySelector(".beta-quick-actions-card");
    if(quick&&!document.getElementById("fuelGuardRoutineToday")){const card=document.createElement("section");card.id="fuelGuardRoutineToday";card.className="beta-rhythm-section-card fg-routine-card";card.setAttribute("aria-label","Routines");quick.insertAdjacentElement("beforebegin",card)}
    const settings=document.getElementById("checklist");if(settings&&!document.getElementById("fuelGuardRoutineSettings")){const a=document.createElement("article");a.id="fuelGuardRoutineSettings";a.className="card fg-routine-settings";settings.appendChild(a)}
    if(!document.getElementById("fuelGuardRoutineSheet"))document.body.insertAdjacentHTML("beforeend",`<section id="fuelGuardRoutineSheet" class="fg-routine-sheet" data-private-ui data-managed-visibility hidden inert aria-modal="true" role="dialog"><button class="fg-routine-sheet-backdrop" type="button" data-routine-close aria-label="Close"></button><article class="fg-routine-sheet-panel"><div class="fg-routine-sheet-handle"></div><header class="fg-routine-sheet-header"><div><span class="fg-routine-eyebrow">Routines first</span><h2>Set up what repeats</h2><p>Choose coffee or supplements here. You do not need to visit Settings first.</p></div><button class="secondary fg-routine-close" type="button" data-routine-close>×</button></header><div id="fuelGuardRoutineSheetBody"></div></article></section>`);
  }
  function selectedKeys(){return new Set(plans.map(catalogueKey).filter(Boolean))}
  function formMarkup(){const current=routines(),selected=selectedKeys();return `<form id="fuelGuardRoutineForm" class="fg-routine-settings-form">
    <div class="fg-routine-step"><span>1</span><div><strong>When does it happen?</strong><small>Name the routine, choose its time and repeat days.</small></div></div>
    <div class="fg-routine-form-grid"><label>Routine name<input name="name" type="text" value="Morning routine" maxlength="60" required></label><label>Time<input name="time" type="time" value="05:30" required></label></div>
    <fieldset><legend>Repeat days</legend><div class="fg-routine-days">${DAYS.map((d,i)=>`<label><input type="checkbox" name="day" value="${i}" ${i>0&&i<6?"checked":""}><span>${d}</span></label>`).join("")}</div></fieldset>
    <div class="fg-routine-step"><span>2</span><div><strong>What happens in this routine?</strong><small>Select supplements directly here. Fuel Guard saves them for you.</small></div></div>
    <fieldset><legend>Items to confirm</legend><div class="fg-routine-supplements"><label class="fg-routine-choice"><input type="checkbox" name="coffee"><span><strong>Coffee</strong><small>Routine confirmation only — not counted as a Fuel event.</small></span></label>${CATALOGUE.map(c=>`<label class="fg-routine-choice"><input type="checkbox" name="supplementKey" value="${esc(c[0])}" ${selected.has(c[0])?"":""}><span><strong>${esc(c[1])}</strong><small>${selected.has(c[0])?"Already available in Fuel Guard · ":""}Select to include in this routine.</small></span></label>`).join("")}</div></fieldset>
    <div class="fg-routine-step"><span>3</span><div><strong>Save once, confirm later</strong><small>The schedule creates an expectation. It never pretends you took something.</small></div></div>
    <button class="primary fg-routine-save" type="submit" ${busy?"disabled":""}>${busy?"Saving…":"Save routine"}</button><p class="fg-routine-note">After the scheduled time: Yes, done confirms it; No, skipped records nothing. Missed questions stay available for 7 days.</p>
    </form>${current.length?`<div class="fg-routine-existing"><h3>Saved routines</h3>${current.map(r=>`<article><div><strong>${esc(r.name)}</strong><div class="fg-routine-saved-grid"><div class="fg-routine-saved-cell"><span>Time</span><strong>${esc(r.time)}</strong></div><div class="fg-routine-saved-cell"><span>Days</span><strong>${esc(daysText(r.days))}</strong></div><div class="fg-routine-saved-cell"><span>Confirms</span><strong>${esc(labels(r).join(" · ")||"Nothing")}</strong></div></div></div><button class="secondary" type="button" data-routine-delete="${esc(r.id)}">Remove</button></article>`).join("")}</div>`:""}`}
  function renderSheet(){const x=document.getElementById("fuelGuardRoutineSheetBody");if(x)x.innerHTML=formMarkup()}
  function open(){ensureSurfaces();renderSheet();const s=document.getElementById("fuelGuardRoutineSheet");s.hidden=false;s.removeAttribute("inert");document.body.classList.add("fg-routine-sheet-open")}
  function close(){const s=document.getElementById("fuelGuardRoutineSheet");if(!s)return;s.hidden=true;s.setAttribute("inert","");document.body.classList.remove("fg-routine-sheet-open")}
  function missed(now=new Date()){const out=[];for(let n=1;n<=LOOKBACK;n++){const d=new Date(now);d.setDate(d.getDate()-n);for(const r of routines()){const p=planned(r,d);if(onDay(r,d)&&p<now&&!occ()[okey(r,d)])out.push({r,p})}}return out.sort((a,b)=>b.p-a.p)}
  function card(r,p,o,isMissed=false){const future=p>new Date(),status=o?.status==="confirmed"?"Confirmed":o?.status==="skipped"?"Skipped":isMissed?"Missed · answer now":future?"Expected":"Confirm now";return `<article class="fg-routine-item ${o?.status||isMissed&&"missed"||future&&"expected"||"due"}"><header><div><h4>${esc(r.name)}</h4><div class="fg-routine-meta">${isMissed?`${esc(dayLabel(p))} · `:""}${esc(clock(p))}</div></div><span class="fg-routine-status">${esc(status)}</span></header><div class="fg-routine-items">${esc(labels(r).join(" · ")||"No items")}</div>${o?`<p class="fg-routine-result">${o.status==="confirmed"?`Recorded for ${esc(clock(p))}`:"Nothing recorded"}</p>`:`<div class="fg-routine-actions"><button class="primary" data-routine-confirm="${esc(r.id)}" data-routine-date="${esc(p.toISOString())}" ${future||busy?"disabled":""}>Yes, done</button><button class="secondary" data-routine-skip="${esc(r.id)}" data-routine-date="${esc(p.toISOString())}" ${future||busy?"disabled":""}>No, skipped</button></div>`}</article>`}
  function renderToday(){const t=document.getElementById("fuelGuardRoutineToday");if(!t)return;const now=new Date(),rs=routines();t.hidden=false;if(!rs.length){t.innerHTML=`<div class="fg-routine-onboarding"><div><span class="fg-routine-eyebrow">Start here · Routines</span><h3>Set up the things you repeat.</h3><p>Coffee every morning? Creatine and multivitamin on weekdays? Build that first, then use manual logging below whenever life does not follow the routine.</p></div><button class="primary fg-routine-start" data-routine-open>Set up my routine</button></div>`;return}const due=rs.filter(r=>onDay(r,now)),m=missed(now);t.innerHTML=`<div class="fg-routine-title-row"><div><span class="fg-routine-eyebrow">Start here · Routines</span><h3>Your routine</h3><p>Confirm the repeat stuff first. Manual logging is just below for anything extra.</p></div><button class="secondary" data-routine-open>Manage</button></div>${m.length?`<div class="fg-routine-missed-heading">Still needs an answer</div><div class="fg-routine-list">${m.map(x=>card(x.r,x.p,null,true)).join("")}</div>`:""}${due.length?`<div class="fg-routine-list">${due.map(r=>card(r,planned(r,now),occ()[okey(r,now)])).join("")}</div>`:`<div class="fg-routine-offday"><strong>No routine due today.</strong><span>Use manual logging below if something happens outside your routine.</span></div>`}<p class="fg-routine-message">${esc(message)}</p>`}
  function renderSettings(){const t=document.getElementById("fuelGuardRoutineSettings");if(t)t.innerHTML=`<div class="fg-routine-settings-summary"><div><span class="fg-routine-eyebrow">Routines</span><h2>Recurring moments</h2><p>Routines are managed from Daily first. Settings remains a secondary route.</p></div><button class="primary" data-routine-open>Manage routines</button></div>`}
  async function record(r,p){const ps=activeFor(r);if(!ps.length)return;const tz=Intl.DateTimeFormat().resolvedOptions().timeZone||"UTC",snap=window.FuelGuardContextLayer?.contextSnapshot?.(p)||{primary:"everyday",capturedAt:new Date().toISOString()};const rows=ps.map(x=>({id:id(),user_id:uid(),supplement_plan_id:x.id,schedule_slot_id:null,event_status:"taken",taken_at:p.toISOString(),planned_for:p.toISOString(),source:"manual",idempotency_key:`routine:${r.id}:${x.id}:${dateKey(p)}`,event_local_date:dateKey(p),timezone_name:tz,context_mode:snap.primary||"everyday",context_snapshot:snap}));const {error}=await cloud().client.from("fuel_supplement_events").insert(rows);if(error)throw error;await window.FuelGuardSupplementRhythm?.load?.()}
  async function confirm(rid,iso){const r=routines().find(x=>x.id===rid),p=new Date(iso);if(!r||busy||p>new Date())return;busy=true;renderToday();try{await record(r,p);const o=occ();o[okey(r,p)]={status:"confirmed",plannedAt:p.toISOString(),confirmedAt:new Date().toISOString(),coffee:!!r.coffee,supplementPlanIds:[...(r.supplementPlanIds||[])]};saveO(o);message=`Confirmed for ${clock(p)}.`}catch(e){message=`Could not confirm: ${e.message||"try again"}`}finally{busy=false;